var productos = [
    {id:"1", codigo:"LUX001", ml:90, marca:"Afnan", nombre:"Turathi Blue for Men", precio:28000, stock:10, stockCritico:2, categoria:"moderados", familia:"acuatico", estacion:"verano", genero:"hombre", tipo:"arabe", concentracion:"edp", humor:["fresco","elegante"], maridaje:["dia_a_dia","trabajo_reuniones"], notas:{salida:["Citricos"], corazon:["Notas amaderadas","Ambar"], fondo:["Almizcle blanco","Especias", "Pachuli"]}, imagen:"https://www.eliteperfumes.cl/cdn/shop/files/afnan-afnan-turathi-hombre-edp-90-ml-h-31769510346788.jpg?v=1699980010&width=900", descripcion:"Una fragancia cítrica y amaderada ultra limpia, dominada por un vibrante pomelo jugoso sobre una base de ámbar sofisticado. Es un aroma fresco y elegante, ideal para el uso diario y la oficina, que destaca por su excelente duración en climas cálidos.",inspiradoEn:{marca:"Bvlgari", nombre:"Tygar", precioOriginal:476490}},
    {id:"2", codigo:"LUX002", ml:100, marca:"Afnan", nombre:"9pm", precio:25000, stock:8, stockCritico:2, categoria:"intensos", familia:"avainillado", estacion:"invierno", genero:"hombre", tipo:"arabe", concentracion:"edp", humor:["poderoso","romantico"], maridaje:["cita_romantica","noche_especial"], notas:{salida:["Manzana","Canela", "lavanda silvestre", "bergamota"], corazon:["Flor de azahar del naranjo","Lirio de los valles (muguete)"], fondo:["Vainilla","Haba tonka", "Ambar", "Pachuli"]}, imagen:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTN1Yjy3dn9sLbw0SRYQokbFynHewjNF4R9Ex-GGHBwkVHUZXXsCM28v27m&s=10", descripcion:"Una fragancia dulce y seductora, dominada por una salida de manzana crujiente que evoluciona hacia una base densa de vainilla y canela. Es un aroma potente y magnético, ideal para fiestas y citas, que destaca por su proyección enorme y duración extrema en la noche."},
    {id:"3", codigo:"LUX003", ml:50, marca:"Dior", nombre:"Miss Dior Eau de Parfum (2021)", precio:198400, stock:6, stockCritico:2, categoria:"moderados", familia:"floral", estacion:"primavera", genero:"mujer", tipo:"disenador", concentracion:"edp", humor:["romantico","elegante"], maridaje:["cita_romantica","noche_especial"], notas:{salida:["Iris","Peonía", "Lirio de los valles (muguete)"], corazon:["Rosa","Chabacano", "Durazno"], fondo:["Vainilla","Almizcle", "Haba Tonka", "Sandalo", "Benjui"]}, imagen:"https://media.falabella.com/falabellaCL/15535785_3/w=1200,h=1200,fit=pad", descripcion:"Una fragancia floral, elegante y romántica, con un carácter femenino y sofisticado."},
    {id:"4", codigo:"LUX004", ml:100, marca:"Valentino", nombre:"Donna Born In Roma", precio:159990, stock:4, stockCritico:1, categoria:"moderados", familia:"floral", estacion:"primavera", genero:"mujer", tipo:"disenador", concentracion:"edp", humor:["romantico", "elegante"], maridaje:["cita_romantica", "noche_especial", "dia_a_dia"], notas:{salida:["Grosellas negras","Pimienta rosa", "Bergamota"], corazon:["Jazmin","Jazmin sabac", "Te del jazmin"], fondo:["Vainilla Bourbon", "Cachemira", "Madera de gaiac"]}, imagen:"https://dbs.cl/media/catalog/product/v/a/valentino-vno-76144-4.jpg?optimize=low&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:", descripcion:"Una fragancia de alta costura, cálida y floral con una vibrante mezcla de jazmín y vainilla Bourbon.", inspiradoEn:{marca:"Tom Ford", nombre:"Tobacco Vanille", precioOriginal:380000}},
    {id:"5", codigo:"LUX005", ml:100, marca:"Versace", nombre:"Eros", precio:69990, stock:9, stockCritico:2, categoria:"moderados", familia:"avainillado", estacion:"primavera", genero:"hombre", tipo:"disenador", concentracion:"edt", humor:["poderoso"], maridaje:["noche_especial","cita_romantica"], notas:{salida:["Menta","Manzana verde", "Limon"], corazon:["Haba tonka","Ambroxan", "Geranio"], fondo:["Vainilla de Madagascar","Cedro de virginia", "Cedro del atlas", "Vetiver", "Musgo de roble"]}, imagen:"https://fimgs.net/photogram/p1200/xu/dd/sjhF2oPsrTWGj1R7.jpg", descripcion:"Es una fragancia vibrante, seductora y con mucha presencia. Destaca por un contraste entre una salida fresca de menta, manzana verde y limón, que rápidamente da paso a un fondo cálido, dulce y envolvente dominado por la vainilla, el haba tonka y maderas de cedro. Es ideal para destacar en la noche, salidas informales o citas donde busques dejar huella."},
    {id:"6", codigo:"LUX006", ml:125, marca:"Jean Paul Gaultier", nombre:"Le Beau Le Parfum", precio:117990, stock:7, stockCritico:2, categoria:"moderados", familia:"gourmand", estacion:"verano", genero:"hombre", tipo:"disenador", concentracion:"edp", humor:["romantico", "poderoso"], maridaje:["playa","noche_especial", "cita_romantica"], notas:{salida:["Piña","Iris", "Jengibre", "Cipres"], corazon:["Coco","Notas amaderadas"], fondo:["Haba tonka","Sandalo", "Ambar", "Ambar gris"]}, imagen:"https://fimgs.net/photogram/p1200/ue/l8/0IZYXSzIvUm7OkMc.jpg", descripcion:"Es una fragancia exótica, ultra atractiva y densa que combina la frescura tropical con una base profundamente dulce y cálida. Su acorde estrella mezcla un coco cremoso y ahumado con madera de sándalo, tonka y un toque de piña jugosa. Es un aroma adictivo y de gran proyección, perfecto para noches de verano, salidas de fiesta o citas románticas donde busques destacar."},
    {id:"7", codigo:"LUX007", ml:75, marca:"Parfums de Marly", nombre:"Delina Exclusif", precio:364990, stock:12, stockCritico:2, categoria:"intensos", familia:"floral", estacion:"primavera", genero:"mujer", tipo:"nicho", concentracion:"parfum", humor:["elegante", "romantico"], maridaje:["noche_especial","evento_exclusivo", "cita_romantica", "gala", "boda"], notas:{salida:["Lichi","Pera", "Bergamota", "Pimienta Rosa", "Toronja"], corazon:["Rosa Turca","Madera de oud", "Incienso"], fondo:["Vainilla","Ambar", "Notas amaderadas", "Almizcle", "Evernil", "Vetiver"]}, imagen:"https://fimgs.net/photogram/p1200/qq/ho/b5y2gJ4LoiKF58Qd.jpg", descripcion:"Delina Exclusif es una fragancia opulenta, sensual y extremadamente sofisticada. Toma el ADN de rosa y lichi del Delina original y lo lleva a un terreno más denso, cremoso y nocturno, incorporando notas sensuales de incienso, ámbar y una vainilla sumamente suave y abizcochada. Es un aroma elegante y envolvente con una fijación extraordinaria, concebido para ocasiones especiales donde quieras proyectar distinción y glamour absoluto.."},
    {id:"8", codigo:"LUX008", ml:50, marca:"Xerjoff", nombre:"XJ 1861 Naxos", precio:219990, stock:3, stockCritico:1, categoria:"intensos", familia:"oriental", estacion:"invierno", genero:"unisex", tipo:"nicho", concentracion:"edp", humor:["elegante","poderoso", "misterioso"], maridaje:["noche_especial","evento_exclusivo", "cita_romantica", "trabajo_reuniones", "gala"], notas:{salida:["Lavanda","Bergamota", "Limon"], corazon:["Miel","Canela", "Cachemira", "Jazmin sambac"], fondo:["Hojas de tabaco","Vainilla", "Habatonka"]}, imagen:"https://fimgs.net/photogram/p1200/ks/63/viIeYrLTzoakkieZ.jpg", descripcion:"XJ 1861 Naxos de Xerjoff es un tributo a la riqueza y tradición de Sicilia, ofreciendo un aroma suntuoso, cálido y sumamente sofisticado. Destaca por una combinación magistral de miel dorada y tabaco dulce, equilibrada en su apertura por un toque brillante de lavanda y cítricos, para luego asentarse en una base cremosa de vainilla, haba tonka y canela. Es una fragancia versátil dentro de la alta perfumería, con presencia imponente pero extremadamente refinada, ideal para climas templados o fríos y eventos donde la elegancia sea protagonista."},
    {id:"9", codigo:"LUX009", ml:100, marca:"Dumont", nombre:"Nitro Red", precio:27990, stock:10, stockCritico:2, categoria:"intensos", familia:"frutal", estacion:"verano", genero:"hombre", tipo:"arabe", concentracion:"edp", humor:["fresco","poderoso"], maridaje:["playa","dia_a_dia","noche_especial"], notas:{salida:["Manzana","Lavanda","Bergamota"], corazon:["Sandía","Cedro","Cálamo aromático"], fondo:["Ámbar","Sándalo","Pachulí"]}, imagen:"https://fimgs.net/photogram/p1200/6g/8s/bZuLdAW7wKZY7PaH.jpg", descripcion:"Una fragancia vibrante, dulce y sumamente llamativa. Destaca por una salida muy frutal donde brilla una refrescante nota de sandía y manzana, para luego asentarse en un fondo amaderado y ambarino que le da mucha potencia. Con un rendimiento bestial, es ideal para destacar en climas cálidos, salidas informales o en la playa.", inspiradoEn:{marca:"Paco Rabanne", nombre:"Invictus", precioOriginal:109990}},
    {id:"10", codigo:"LUX010", ml:100, marca:"Dumont", nombre:"Nitro Elixir", precio:28990, stock:10, stockCritico:2, categoria:"intensos", familia:"gourmand", estacion:"otono", genero:"hombre", tipo:"arabe", concentracion:"edp", humor:["elegante","misterioso"], maridaje:["noche_especial","cita_romantica"], notas:{salida:["Bergamota","Manzana","Cardamomo","Naranja"], corazon:["Flor de azahar del naranjo","Praliné","Menta","Geranio"], fondo:["Ámbar gris","Haba tonka","Ámbar","Musgo"]}, imagen:"https://beautyexpresspr.com/cdn/shop/files/645fd9fe-a616-4903-9be9-eefc94a6ef14.png?v=1778946349&width=1200", descripcion:"Una fragancia moderna y magnética. Su salida cítrica y especiada abre paso a un corazón sorprendente donde la flor de azahar se funde con el dulzor del praliné y el frescor de la menta. Su fondo cálido de ámbar y haba tonka le otorga una estela seductora, perfecta para la noche y ocasiones especiales.", inspiradoEn:{marca:"Yves Saint Laurent", nombre:"MYSLF L'Absolu", precioOriginal:149990}},
    {id:"11", codigo:"LUX011", ml:100, marca:"Dumont", nombre:"Nitro Gold", precio:37990, stock:10, stockCritico:2, categoria:"moderados", familia:"amaderado", estacion:"primavera", genero:"unisex", tipo:"arabe", concentracion:"edp", humor:["fresco","elegante"], maridaje:["dia_a_dia","noche_especial"], notas:{salida:["Manzana","Pimienta rosa","Pimienta negra","Toronja (pomelo)","Piña","Naranja tangerina"], corazon:["Sal","Notas marinas","Cedro","Coñac","Vetiver"], fondo:["Amberwood","Sándalo","Almizcle","Tófe","Vainilla"]}, imagen:"https://luxuryperfumesarabes.cl/wp-content/uploads/2026/06/2_8e58c6fd-39d8-4fb4-aeae-b39460a6b03d.webp", descripcion:"Una fragancia unisex versátil y cautivadora. Inicia con una explosión frutal y especiada de piña, cítricos y pimienta, que da paso a un corazón contrastante de notas marinas, sal y coñac. Su base cálida de vainilla, tófe y maderas ambaradas le aporta una estela elegante y muy duradera.", inspiradoEn:{marca:"Valentino", nombre:"Valentino Uomo Born in Roma", precioOriginal:129990}},
    {id:"12", codigo:"LUX012", ml:100, marca:"Afnan", nombre:"9 PM Night Out", precio:42990, stock:10, stockCritico:2, categoria:"intensos", familia:"gourmand", estacion:"invierno", genero:"unisex", tipo:"arabe", concentracion:"edp", humor:["poderoso","misterioso"], maridaje:["noche_especial","cita_romantica","evento_exclusivo"], notas:{salida:["Pitahaya","Lavanda","Coñac","Manzana","Bergamota"], corazon:["Tófe","Gamuza","Cardamomo","Cedro","Mahonial"], fondo:["Haba tonka","Akigalawood","Ambrofix™","Pachulí"]}, imagen:"https://cosmetic.cl/cdn/shop/files/9_ab103946-5d5b-4a24-acc5-cbb0ef5e2583_800x.png?v=1769454599", descripcion:"Una fragancia nocturna, potente y seductora. Abre con una mezcla exótica de pitahaya y un toque embriagador de coñac, dando paso a un corazón cálido y dulce de tófe y gamuza. Su base rica en maderas y haba tonka garantiza una estela envolvente, ideal para dejar huella en la noche.", inspiradoEn:{marca:"Azzaro", nombre:"Forever Wanted Elixir", precioOriginal:75000}},
    {id:"13", codigo:"LUX013", ml:100, marca:"Hugo Boss", nombre:"Boss The Scent Elixir For Him", precio:169990, stock:10, stockCritico:2, categoria:"intensos", familia:"especiado", estacion:"invierno", genero:"hombre", tipo:"disenador", concentracion:"parfum", humor:["poderoso","misterioso"], maridaje:["noche_especial","cita_romantica"], notas:{salida:["Chile rojo (ají rojo)"], corazon:["Lavanda"], fondo:["Sándalo"]}, imagen:"https://i5.walmartimages.cl/asr/155346b3-27a0-4a88-83cb-fa37ab28fb5f.40bf4d6021871127eceef8b1a1e73c42.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF", descripcion:"Un elixir ardiente y altamente concentrado. Su apertura impacta con el calor vibrante del chile rojo, que se equilibra a la perfección con un corazón aromático de lavanda. Finalmente, descansa sobre una base rica y cremosa de sándalo, creando una estela seductora, cálida y profundamente masculina."},
    {id:"14", codigo:"LUX014", ml:125, marca:"Jean Paul Gaultier", nombre:"Le Beau Paradise Garden", precio:153990, stock:10, stockCritico:2, categoria:"moderados", familia:"acuatico", estacion:"verano", genero:"hombre", tipo:"disenador", concentracion:"edp", humor:["fresco","relajado"], maridaje:["playa","dia_a_dia"], notas:{salida:["Notas verdes","Notas acuosas","Menta","Jengibre"], corazon:["Coco","Higo","Sal"], fondo:["Haba tonka","Sándalo"]}, imagen:"https://media.falabella.com/falabellaCL/50369047_6/w=1500,h=1500,fit=cover", descripcion:"Una escapada a un jardín tropical. Abre con un frescor vibrante de notas verdes, menta y acordes acuosos. En su corazón, la mezcla exótica de coco e higo se realza con un toque de sal, aportando una cremosidad adictiva. Su fondo de haba tonka y sándalo lo envuelve en una estela seductora, ideal para días de verano y ocasiones relajadas."},
    {id:"15", codigo:"LUX015", ml:100, marca:"Giorgio Armani", nombre:"Emporio Armani Stronger With You Intensely", precio:89990, stock:10, stockCritico:2, categoria:"intensos", familia:"gourmand", estacion:"invierno", genero:"hombre", tipo:"disenador", concentracion:"edp", humor:["romantico","poderoso"], maridaje:["cita_romantica","noche_especial"], notas:{salida:["Pimienta rosa","Enebro","Violeta"], corazon:["Tófe","Canela","Lavanda","Salvia"], fondo:["Vainilla","Ámbar","Haba tonka","Gamuza"]}, imagen:"https://cl-dam-resizer.ecomm.cencosud.com/unsafe/adaptive-fit-in/3840x0/filters:quality(75)/cl/paris/206934999/variant/685ac78315a03c31025e0564/images/baaecf13-ece0-4982-a957-76541918144d/206934999-0000-003.jpg", descripcion:"Una fragancia cálida, dulce y profundamente adictiva. Inicia con un toque especiado de pimienta rosa y enebro, envuelto en hojas de violeta. Su corazón irresistible combina la dulzura del tófe y la canela con destellos aromáticos, para finalmente fundirse en un fondo intenso de vainilla, ámbar y gamuza. Es el aroma perfecto para destacar en las noches frías y en citas románticas."},
    {id:"16", codigo:"LUX016", ml:100, marca:"Giorgio Armani", nombre:"Power Of You", precio:96990, stock:10, stockCritico:2, categoria:"moderados", familia:"floral", estacion:"verano", genero:"mujer", tipo:"disenador", concentracion:"edp", humor:["fresco","elegante"], maridaje:["dia_a_dia","playa"], notas:{salida:["Maracuyá (fruta de la pasión)","Naranja amarga","Limón (lima ácida)"], corazon:["Frangipani (plumeria, plumaria, atapaima)","Notas solares"], fondo:["Vainilla de Madagascar","Benjuí","Ládano"]}, imagen:"https://media.falabella.com/falabellaCL/80711328_3/w=1500,h=1500,fit=cover", descripcion:"Una fragancia luminosa y tropical. Abre con la jugosidad exótica del maracuyá y vibrantes toques cítricos, dando paso a un corazón radiante de frangipani y notas solares. Su base cálida de vainilla de Madagascar y benjuí envuelve la piel con un toque dulce y elegante, perfecta para destacar en días soleados."},
    {id:"17", codigo:"LUX017", ml:100, marca:"Jean Paul Gaultier", nombre:"La Belle", precio:121950, stock:10, stockCritico:2, categoria:"intensos", familia:"avainillado", estacion:"otono", genero:"mujer", tipo:"disenador", concentracion:"edp", humor:["romantico","elegante"], maridaje:["cita_romantica","noche_especial"], notas:{salida:["Pera","Bergamota"], corazon:["Notas florales","Cuero"], fondo:["Vainilla","Vetiver","Ámbar","Almizcle"]}, imagen:"https://static.sweetcare.com/img/prd/488/v-638485379091938175/jean-paul-gaultier-011307jg-3.webp", descripcion:"Una fragancia irresistiblemente dulce y seductora. Abre con una nota jugosa y luminosa de pera entrelazada con bergamota, que se funde en un corazón cautivador de notas florales y un toque audaz de cuero. Su base es un adictivo abrazo de vainilla, ámbar, vetiver y almizcle, creando una estela femenina, sensual y perfecta para deslumbrar en ocasiones especiales."},
    {id:"18", codigo:"LUX018", ml:80, marca:"Carolina Herrera", nombre:"Good Girl", precio:109990, stock:10, stockCritico:2, categoria:"intensos", familia:"oriental", estacion:"invierno", genero:"mujer", tipo:"disenador", concentracion:"edp", humor:["poderoso","misterioso","elegante"], maridaje:["noche_especial","cita_romantica"], notas:{salida:["Almendra","Café","Bergamota","Limón (lima ácida)"], corazon:["Nardos","Jazmín sambac (sampaguita)","Flor de azahar del naranjo","Rosa de Bulgaria (rosa Damascena de Bulgaria)","Raíz de lirio"], fondo:["Haba tonka","Cacao","Vainilla","Praliné","Sándalo","Almizcle","Ámbar","Madera de cachemira","Pachulí","Canela","Cedro"]}, imagen:"https://productosdelujo.cl/cdn/shop/products/3CC24099563.jpg?v=1623701251&width=1214", descripcion:"Una fragancia audaz y sofisticada, símbolo de la dualidad femenina. Abre con notas luminosas de almendra y un toque energizante de café. El corazón es un bouquet floral de nardos y jazmín sambac que irradia feminidad, mientras que su fondo profundo y seductor revela notas sumamente adictivas de haba tonka, cacao y vainilla. Perfecta para empoderar tus noches y eventos exclusivos."},
    {id:"19", codigo:"LUX019", ml:100, marca:"Louis Vuitton", nombre:"L'Immensité", precio:462000, stock:10, stockCritico:2, categoria:"moderados", familia:"acuatico", estacion:"verano", genero:"hombre", tipo:"nicho", concentracion:"edp", humor:["fresco","elegante"], maridaje:["dia_a_dia","trabajo_reuniones","evento_exclusivo"], notas:{salida:["Toronja (pomelo)","Bergamota","Jengibre"], corazon:["Romero","Salvia","Geranio","Notas acuáticas"], fondo:["Ambroxan","Ámbar","Ládano"]}, imagen:"https://la.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-perfume-l-immensite--LP0052_PM1_Interior%20view.jpg", descripcion:"Una fragancia refrescante y sofisticada de alta gama. Su apertura vibrante de toronja y jengibre da paso a un corazón aromático y acuático. El fondo de ambroxan y ámbar asegura una estela elegante y persistente, ideal para proyectar exclusividad y frescura en el día a día."},
    {id:"20", codigo:"LUX020", ml:100, marca:"Louis Vuitton", nombre:"Imagination", precio:420000, stock:10, stockCritico:2, categoria:"moderados", familia:"citrico", estacion:"verano", genero:"hombre", tipo:"nicho", concentracion:"edp", humor:["fresco","elegante","relajado"], maridaje:["dia_a_dia","trabajo_reuniones","playa"], notas:{salida:["Cidra","Bergamota de Calabria","Naranja siciliana"], corazon:["Neroli de Túnez","Jengibre nigeriano","Canela de Ceylan"], fondo:["Té negro de China","Ambroxan","Madera de gaiac","Incienso de olíbano (franquincienso)"]}, imagen:"https://la.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-perfume-imagination--LP0219_PM1_Interior%20view.jpg", descripcion:"Una obra maestra cítrica y estimulante. Abre con un estallido luminoso de cítricos italianos, evolucionando hacia un corazón especiado de neroli y jengibre. La magia ocurre en su fondo, donde el té negro de China y el ambroxan crean un aura limpia, lujosa y sumamente adictiva."},
    {id:"21", codigo:"LUX021", ml:100, marca:"Arabiyat Prestige", nombre:"Marwa", precio:39990, stock:10, stockCritico:2, categoria:"moderados", familia:"citrico", estacion:"verano", genero:"hombre", tipo:"arabe", concentracion:"edp", humor:["fresco","elegante"], maridaje:["dia_a_dia","trabajo_reuniones"], notas:{salida:["Bergamota de Calabria","Limón (lima ácida)","Naranja siciliana"], corazon:["Jengibre nigeriano","Canela de Ceylan","Neroli de Túnez"], fondo:["Ambroxan","Té negro de China","Incienso de olíbano (franquincienso)","Madera de gaiac"]}, imagen:"https://http2.mlstatic.com/D_NQ_NP_751711-CBT110859757181_042026-O.webp", descripcion:"Una fragancia vibrante, fresca y sumamente limpia. Abre con un cóctel cítrico brillante, dando paso a un corazón ligeramente especiado de jengibre y canela. Su fondo de té negro y ambroxan le otorga un aura elegante y magnética, ideal para brillar durante el día y en el trabajo.", inspiradoEn:{marca:"Louis Vuitton", nombre:"Imagination", precioOriginal:420000}},
    {id:"22", codigo:"LUX022", ml:50, marca:"Tom Ford", nombre:"Lost Cherry", precio:384990, stock:10, stockCritico:2, categoria:"intensos", familia:"frutal", estacion:"otono", genero:"unisex", tipo:"nicho", concentracion:"edp", humor:["misterioso","elegante"], maridaje:["noche_especial","cita_romantica","evento_exclusivo"], notas:{salida:["Almendra amarga","Cereza negra","Licor de cereza"], corazon:["Cereza ácida (guinda)","Ciruela","Rosa turca","Jazmín sambac (sampaguita)"], fondo:["Vainilla","Haba tonka","Canela","Bálsamo del Perú","Sándalo","Benjuí","Clavos de olor","Cedro","Pachulí","Vetiver"]}, imagen:"https://hypefragrances.cl/wp-content/uploads/2021/11/LOST-CHERRY-2.jpg", descripcion:"Un viaje olfativo exótico, cálido y profundamente dulce. Abre con una explosión intensa de cereza negra, licor y almendra amarga, que se funde en un corazón de ciruela y notas florales. Su fondo es una mezcla opulenta de vainilla, haba tonka y maderas preciosas que crean una estela embriagadora e irresistible."},
    {id:"23", codigo:"LUX023", ml:200, marca:"Versace", nombre:"Eros Flame", precio:75990, stock:10, stockCritico:2, categoria:"intensos", familia:"especiado", estacion:"invierno", genero:"hombre", tipo:"disenador", concentracion:"edp", humor:["poderoso","romantico"], maridaje:["cita_romantica","noche_especial"], notas:{salida:["Mandarina","Pimienta de Madagascar","Limón (lima ácida)","Chinotto","Romero"], corazon:["Geranio","Rosa","Pepperwood™"], fondo:["Vainilla","Haba tonka","Sándalo","Cedro de Texas","Pachulí","Musgo de roble"]}, imagen:"https://aliss.do/media/catalog/product/4/9/498e733a0af2fe685b95f8fbd46c0c9477d15eda_file.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=700&width=700&canvas=700:700", descripcion:"Una fragancia apasionada, cálida y de contrastes. Abre con un golpe cítrico y especiado vibrante gracias a la mandarina y la pimienta negra, para luego revelar un corazón floral intenso. Su base cálida de vainilla, haba tonka y maderas nobles deja una estela poderosa y seductora, perfecta para climas fríos y ocasiones especiales."},
    {id:"24", codigo:"LUX024", ml:100, marca:"Armaf", nombre:"Odyssey Mandarin Sky", precio:34990, stock:10, stockCritico:2, categoria:"intensos", familia:"gourmand", estacion:"otono", genero:"hombre", tipo:"arabe", concentracion:"edp", humor:["poderoso","relajado"], maridaje:["noche_especial","dia_a_dia"], notas:{salida:["Mandarina","Naranja","Azafrán","Salvia"], corazon:["Caramelo","Haba tonka","Cempasúchil (tagete, clavelón)"], fondo:["Ambroxan","Cedro","Vetiver"]}, imagen:"https://perfumeschile.cl/cdn/shop/files/Odyssey-Mandarin-Sky-3.jpg?v=1787240368&width=600", descripcion:"Una fragancia dulce, jugosa y sumamente adictiva. Su salida explosiva de mandarina y naranja se funde rápidamente con un corazón deliciosamente gourmand de caramelo derretido y haba tonka. El fondo de ambroxan y maderas le da un soporte sólido y una proyección bestial, ideal para destacar tanto en salidas nocturnas como en días frescos.", inspiradoEn:{marca:"Jean Paul Gaultier", nombre:"Scandal Pour Homme", precioOriginal:110000}},
    {id:"25", codigo:"LUX025", ml:150, marca:"Jean Paul Gaultier", nombre:"Scandal Pour Homme", precio:124990, stock:10, stockCritico:2, categoria:"intensos", familia:"gourmand", estacion:"invierno", genero:"hombre", tipo:"disenador", concentracion:"edt", humor:["poderoso","romantico"], maridaje:["noche_especial","cita_romantica"], notas:{salida:["Mandarina","Esclarea"], corazon:["Caramelo","Haba tonka"], fondo:["Vetiver"]}, imagen:"https://cl-dam-resizer.ecomm.cencosud.com/unsafe/adaptive-fit-in/3840x0/filters:quality(75)/paris/517296999/variant/images/00056e7c-4391-4c76-bdfe-4b5f642cddd7/517296999-0000-003.jpg", descripcion:"Una fragancia magnética, dulce y audaz. Abre con un toque fresco y aromático de mandarina y esclarea, que rápidamente cede el paso a un corazón adictivo y goloso de caramelo y haba tonka. Su base de vetiver le otorga un anclaje terroso y masculino, creando una estela irresistible perfecta para la noche, fiestas y citas románticas."},
    {id:"26", codigo:"LUX026", ml:200, marca:"Paco Rabanne", nombre:"Invictus Victory", precio:119990, stock:10, stockCritico:2, categoria:"intensos", familia:"oriental", estacion:"invierno", genero:"hombre", tipo:"disenador", concentracion:"edp", humor:["poderoso","misterioso"], maridaje:["noche_especial","cita_romantica"], notas:{salida:["Pimienta rosa","Limón (lima ácida)"], corazon:["Incienso de olíbano (franquincienso)","Lavanda"], fondo:["Vainilla","Haba tonka","Ámbar"]}, imagen:"https://cl-dam-resizer.ecomm.cencosud.com/unsafe/adaptive-fit-in/3840x0/filters:quality(75)/cl/paris/724216999/variant/69c528b46a2ef0119c97fc2d/images/e2f18eb2-70ad-40cb-bcb1-4ee8c375cd44/724216999-0000-004.jpg", descripcion:"Una fragancia intensa, dulce y sumamente cautivadora. Abre con un contraste vibrante de limón y pimienta rosa, que da paso a un corazón misterioso de incienso y lavanda. Su fondo revela una calidez magnética con vainilla, haba tonka y ámbar, creando una estela poderosa y seductora, perfecta para la noche y climas fríos."},
    {id:"27", codigo:"LUX027", ml:100, marca:"Rayhaan", nombre:"Wolf", precio:36000, stock:10, stockCritico:2, categoria:"intensos", familia:"gourmand", estacion:"invierno", genero:"hombre", tipo:"arabe", concentracion:"edp", humor:["poderoso","misterioso"], maridaje:["noche_especial","cita_romantica"], notas:{salida:["Cardamomo"], corazon:["Tófe"], fondo:["Amberwood"]}, imagen:"https://yauras.cl/cdn/shop/files/There_sadifferencebetweenbeingseen_.andbeingremembered.Onefades.....andtheotherstays_525x700.webp?v=1779811334", descripcion:"Una fragancia cálida, dulce y sumamente seductora. Su apertura especiada de cardamomo capta la atención de inmediato, dando paso a un corazón goloso e irresistible de tófe. El fondo de amberwood le otorga profundidad, potencia y una duración excepcional, convirtiéndola en el arma perfecta para citas y noches de invierno.", inspiradoEn:{marca:"Azzaro", nombre:"The Most Wanted", precioOriginal:89990}},
    {id:"28", codigo:"LUX028", ml:100, marca:"Rayhaan", nombre:"Tropical Vibe", precio:25990, stock:10, stockCritico:2, categoria:"moderados", familia:"frutal", estacion:"verano", genero:"unisex", tipo:"arabe", concentracion:"edp", humor:["fresco","relajado"], maridaje:["playa","dia_a_dia"], notas:{salida:["Mango","Piña","Bergamota","Ron"], corazon:["Coco","Flores blancas","Notas marinas"], fondo:["Almizcle","Ámbar","Sándalo","Vetiver"]}, imagen:"https://www.lodoro.cl/cdn/shop/files/01CACYIAMBLOUPEPWS2050_81_1024x.png?v=1778598697", descripcion:"Un cóctel tropical embotellado. Abre con una jugosa mezcla de mango, piña y un toque embriagador de ron, evocando instantáneamente un ambiente festivo. Su corazón aporta cremosidad con coco y brisa salada, mientras que el fondo de almizcle y sándalo prolonga la sensación de piel cálida bajo el sol. Ideal para vacaciones y días calurosos.", inspiradoEn:{marca:"Lorenzo Pazzaglia", nombre:"Summer Hammer", precioOriginal:158000}},
    {id:"29", codigo:"LUX029", ml:50, marca:"Lorenzo Pazzaglia", nombre:"Summer Hammer", precio:158000, stock:10, stockCritico:2, categoria:"intensos", familia:"frutal", estacion:"verano", genero:"unisex", tipo:"nicho", concentracion:"parfum", humor:["poderoso","relajado"], maridaje:["playa","evento_exclusivo","noche_especial"], notas:{salida:["Mango","Piña","Coco","Bergamota","Ron blanco"], corazon:["Leche de coco","Flores blancas","Notas marinas"], fondo:["Almizcle","Sándalo","Ámbar","Vetiver"]}, imagen:"https://odorare.fr/cdn/shop/files/summer-hammer-lorenzo-pazzaglia-extrait-de-parfum-50ml-ambiance-tropicale_4b09825c-f5a2-4569-86d2-cddb4a6f989c.png?v=1784465904&width=1254", descripcion:"Una experiencia olfativa de lujo absoluta que captura la esencia del verano eterno. Este extracto de perfume abre con una opulenta y densa mezcla de frutas exóticas bañadas en ron blanco. Su corazón revela una textura cremosa de leche de coco entrelazada con acordes salados, descansando sobre una base rica en ámbar y sándalo. Su rendimiento es extraordinario, proyectando una vibra tropical sofisticada y persistente."},
    {id:"30", codigo:"LUX030", ml:100, marca:"Dior", nombre:"Sauvage Elixir", precio:229990, stock:10, stockCritico:2, categoria:"intensos", familia:"especiado", estacion:"invierno", genero:"hombre", tipo:"disenador", concentracion:"parfum", humor:["poderoso","misterioso","elegante"], maridaje:["noche_especial","evento_exclusivo"], notas:{salida:["Nuez moscada","Canela","Cardamomo","Toronja (pomelo)"], corazon:["Lavanda"], fondo:["Regaliz","Sándalo","Ámbar","Pachulí","Vetiver de Haití"]}, imagen:"https://media.falabella.com/falabellaCL/50190731_7/w=1500,h=1500,fit=cover", descripcion:"Una reinterpretación audaz y sumamente concentrada. Abre con un golpe cálido y especiado de nuez moscada, canela y cardamomo, contrastado con la frescura de la toronja. Su corazón puro de lavanda descansa sobre un fondo oscuro y opulento de regaliz, sándalo y ámbar. Es una fragancia imponente, de duración extrema, diseñada para dejar huella en la noche."},
    {id:"31", codigo:"LUX031", ml:100, marca:"Xerjoff", nombre:"Erba Pura", precio:199990, stock:10, stockCritico:2, categoria:"intensos", familia:"frutal", estacion:"primavera", genero:"unisex", tipo:"nicho", concentracion:"edp", humor:["fresco","elegante"], maridaje:["dia_a_dia","evento_exclusivo"], notas:{salida:["Naranja siciliana","Bergamota de Calabria","Limón siciliano (lima siciliana)"], corazon:["Frutas"], fondo:["Almizcle blanco","Vainilla de Madagascar","Ámbar"]}, imagen:"https://fenixperfumes.cl/cdn/shop/files/xerjoff-erba-pura-ultra-lujoso.png?v=1769030518", descripcion:"Una exquisita y moderna mezcla de cítricos mediterráneos dulces envueltos en un aura de lujo. Su salida vibrante de naranja y bergamota da paso a un corazón sumamente jugoso y frutal. El secreto de su estela inmensa radica en su fondo de almizcle blanco, ámbar y vainilla, creando una fragancia aterciopelada, brillante y adictiva."},
    {id:"32", codigo:"LUX032", ml:100, marca:"Valentino", nombre:"Valentino Uomo Born In Roma Coral Fantasy", precio:159900, stock:10, stockCritico:2, categoria:"moderados", familia:"amaderado", estacion:"otono", genero:"hombre", tipo:"disenador", concentracion:"edt", humor:["fresco","romantico"], maridaje:["dia_a_dia","cita_romantica"], notas:{salida:["Manzana roja","Cardamomo","Bergamota de Calabria"], corazon:["Lavanda","Geranio bourbon","Esclarea"], fondo:["Hojas de tabaco","Pachulí","Vetiver de Haití"]}, imagen:"https://i0.wp.com/dperfumes.cl/wp-content/uploads/2024/04/Valentino-Uomo-Born-In-Roma-Coral-Fantasy-Eau-de-Toilette-01.webp?fit=1200%2C1200&ssl=1", descripcion:"Una fragancia vibrante y de grandes contrastes. Abre con un acorde jugoso y llamativo de manzana roja entrelazado con cardamomo y bergamota. Su corazón aromático de lavanda y geranio descansa sobre una base profunda y sumamente masculina de hojas de tabaco y vetiver. Un aroma ideal para destacar con un toque moderno, seductor y atrevido."},
    {id:"33", codigo:"LUX033", ml:100, marca:"Maison Martin Margiela", nombre:"By the Fireplace", precio:124990, stock:10, stockCritico:2, categoria:"intensos", familia:"amaderado", estacion:"invierno", genero:"unisex", tipo:"nicho", concentracion:"edt", humor:["misterioso","relajado"], maridaje:["noche_especial","cita_romantica"], notas:{salida:["Clavos de olor","Pimienta rosa","Flor de azahar del naranjo"], corazon:["Castaña","Madera de gaiac","Enebro"], fondo:["Vainilla","Bálsamo del Perú","Cachemira"]}, imagen:"https://laconicum.com/cdn/shop/files/by-the-fireplace-9845085.png?v=1755162591&width=1080", descripcion:"Un aroma acogedor y nostálgico que evoca el calor de una chimenea en pleno invierno. Combina el toque ahumado de la madera de gaiac y las castañas asadas con la dulzura reconfortante de la vainilla y el bálsamo del Perú. Ideal para climas fríos, creando un aura cálida y sumamente íntima."},
    {id:"34", codigo:"LUX034", ml:70, marca:"Maison Francis Kurkdjian", nombre:"Baccarat Rouge 540", precio:375000, stock:10, stockCritico:2, categoria:"intensos", familia:"oriental", estacion:"otono", genero:"unisex", tipo:"nicho", concentracion:"edp", humor:["elegante","poderoso"], maridaje:["evento_exclusivo","noche_especial","gala"], notas:{salida:["Azafrán","Jazmín"], corazon:["Amberwood","Ámbar gris","Hedione"], fondo:["Resina de abeto","Cedro","Azúcar","Ambroxan","Musgo de roble"]}, imagen:"https://fimgs.net/photogram/p1200/ti/km/3rZsvmRo0o1hweST.jpg", descripcion:"Una obra maestra de la perfumería nicho, luminosa y sofisticada. Su firma olfativa es inconfundible, mezclando la brisa floral del jazmín y el azafrán con las facetas minerales del ámbar gris y los tonos amaderados del cedro. Una fragancia lujosa, magnética y de estela inolvidable que denota pura exclusividad."},
    {id:"35", codigo:"LUX035", ml:50, marca:"By Kilian", nombre:"Angels' Share", precio:436000, stock:10, stockCritico:2, categoria:"intensos", familia:"gourmand", estacion:"invierno", genero:"unisex", tipo:"nicho", concentracion:"edp", humor:["elegante","misterioso"], maridaje:["noche_especial","evento_exclusivo","cita_romantica"], notas:{salida:["Coñac"], corazon:["Canela","Haba tonka","Roble","Hedione"], fondo:["Vainilla","Praliné","Sándalo","Almendras acarameladas"]}, imagen:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpMelhbQ4Glmp3CyDg-x6v2Vua99iK0vAMtj3677uQ4hze6hQqe4jk5I-1&s=10", descripcion:"Una fragancia embriagadora y opulenta que rinde homenaje al coñac más fino. Su apertura licorosa se sumerge rápidamente en un corazón cálido de canela y roble, para terminar en un fondo absolutamente delicioso de praliné, vainilla y almendras acarameladas. Perfecta para quienes buscan un aroma exclusivo, dulce y muy nocturno."},
];

var regiones = [
    {nombre:"Región Metropolitana", comunas:["Santiago","Maipú","Puente Alto","Las Condes","Providencia","La Florida","Ñuñoa"]},
    {nombre:"Valparaíso", comunas:["Valparaíso","Viña del Mar","Quilpué","Villa Alemana","San Antonio"]},
    {nombre:"Biobío", comunas:["Concepción","Talcahuano","Los Ángeles","Chiguayante","San Pedro de la Paz"]},
    {nombre:"La Araucanía", comunas:["Temuco","Villarrica","Pucón","Angol"]},
    {nombre:"Coquimbo", comunas:["La Serena","Coquimbo","Ovalle","Illapel"]},
    {nombre:"O'Higgins", comunas:["Rancagua","San Fernando","Rengo","Machalí"]},
    {nombre:"Maule", comunas:["Talca","Curicó","Linares","Constitución"]},
    {nombre:"Los Lagos", comunas:["Puerto Montt","Osorno","Castro","Puerto Varas"]},
    {nombre:"Antofagasta", comunas:["Antofagasta","Calama","Tocopilla"]},
    {nombre:"Ñuble", comunas:["Chillán","San Carlos","Bulnes"]}
];

var usuarios = JSON.parse(localStorage.getItem("usuarios") || "[]");

if (usuarios.length === 0) {
    usuarios.push({
        run:"19011022K",
        nombre:"Administrador",
        apellidos:"Luxury",
        correo:"admin@duoc.cl",
        password:"admin123",
        fechaNacimiento:"",
        tipo:"Administrador",
        region:"Región Metropolitana",
        comuna:"Santiago",
        direccion:"Casa matriz Luxury"
    });
    localStorage.setItem("usuarios", JSON.stringify(usuarios));
}

function obtenerProductos() {
    var productosGuardados = JSON.parse(localStorage.getItem("productos") || "null");

    if (productosGuardados === null) {
        localStorage.setItem("productos", JSON.stringify(productos));
        return productos;
    }

    return productosGuardados;
}
