// Usuarios iniciales (semilla). Se cargan solo si localStorage esta vacio.
export const usuarios = [
  {
    run: "19011022K",
    nombre: "Administrador",
    apellidos: "Luxury",
    correo: "admin@duoc.cl",
    password: "admin123",
    fechaNacimiento: "",
    tipo: "Administrador",
    region: "Región Metropolitana",
    comuna: "Santiago",
    direccion: "Casa matriz Luxury",
  },
  {
    run: "15234567K",
    nombre: "Valentina",
    apellidos: "Rojas",
    correo: "vendedor@duoc.cl",
    password: "vende123",
    fechaNacimiento: "1995-04-12",
    tipo: "Vendedor",
    region: "Región Metropolitana",
    comuna: "Providencia",
    direccion: "Sucursal Providencia 123",
  },
  {
    run: "20987654K",
    nombre: "Camila",
    apellidos: "Soto",
    correo: "cliente@gmail.com",
    password: "cliente123",
    fechaNacimiento: "2000-08-30",
    tipo: "Cliente",
    region: "Valparaíso",
    comuna: "Viña del Mar",
    direccion: "Av. Perú 456",
  },
];
