import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { usuariosService } from "../../services/usuariosService";

const inicial = { run:"", nombre:"", apellidos:"", correo:"", password:"", confirmar:"", fechaNacimiento:"", region:"", comuna:"", direccion:"" };
export default function Registro() {
  const [datos, setDatos] = useState(inicial); const [error,setError] = useState(""); const [exito,setExito] = useState(""); const [guardando,setGuardando] = useState(false); const navigate=useNavigate();
  const cambiar=e=>setDatos({...datos,[e.target.name]:e.target.value});
  async function enviar(e){e.preventDefault();setError("");setExito("");if(datos.password.length<6){setError("La contraseña debe tener al menos 6 caracteres.");return;}if(datos.password!==datos.confirmar){setError("Las contraseñas no coinciden.");return;}setGuardando(true);try{const existentes=await usuariosService.listar(`?correo=${encodeURIComponent(datos.correo.trim().toLowerCase())}`);if(existentes.length){setError("Ya existe una cuenta registrada con ese correo.");return;}const {confirmar,...nuevo}=datos;await usuariosService.crear({...nuevo,run:nuevo.run.trim().toUpperCase(),correo:nuevo.correo.trim().toLowerCase(),tipo:"Cliente"});setExito("¡Tu cuenta fue creada! Ya puedes iniciar sesión.");setTimeout(()=>navigate("/login"),900);}catch{setError("No se pudo crear la cuenta. Verifica que la API esté disponible e inténtalo nuevamente.");}finally{setGuardando(false);}}
  return <section className="container py-5" style={{maxWidth:900}}><div className="text-center mb-4"><span className="text-uppercase tracking-wider text-gold-light small">Forma parte de Luxury</span><h1 className="display-5 mt-2">Crear cuenta</h1><p className="text-secondary">Regístrate para guardar tus preferencias y agilizar tus compras.</p></div><div className="card luxury-card p-4 p-md-5"><form onSubmit={enviar}><div className="row g-3">
    {[['run','RUT','12345678-9','text'],['nombre','Nombre','Tu nombre','text'],['apellidos','Apellidos','Tus apellidos','text'],['correo','Correo electrónico','tu@correo.com','email'],['fechaNacimiento','Fecha de nacimiento','','date'],['region','Región','Región Metropolitana','text'],['comuna','Comuna','Santiago','text'],['direccion','Dirección','Calle y número','text'],['password','Contraseña','Mínimo 6 caracteres','password'],['confirmar','Confirmar contraseña','Repite tu contraseña','password']].map(([name,label,placeholder,type])=><div className="col-12 col-md-6" key={name}><label className="form-label" htmlFor={`registro-${name}`}>{label}</label><input id={`registro-${name}`} className="form-control form-luxury" name={name} type={type} placeholder={placeholder} required value={datos[name]} onChange={cambiar} autoComplete={name==='password'?'new-password':name==='correo'?'email':'on'} /></div>)}
  </div>{error&&<div className="alert alert-danger mt-3" role="alert">{error}</div>}{exito&&<div className="alert alert-success mt-3" role="status">{exito}</div>}<button className="btn btn-luxury w-100 mt-4" disabled={guardando}>{guardando?'Creando cuenta…':'Crear cuenta'}</button></form><p className="text-center mt-4 mb-0">¿Ya tienes cuenta? <Link to="/login" className="text-gold-light">Inicia sesión</Link></p></div></section>;
}
