import { Link, useParams } from "react-router-dom";
import { useEffect, useState } from "react";
import { ordenesService } from "../../services/ordenesService";
import { formatearPrecio } from "../../utils/formato";
export default function BoletaOrden() {
 const { id } = useParams(); const [orden, setOrden] = useState(null); const [cargando, setCargando] = useState(true); const [error, setError] = useState(null);
 useEffect(() => { ordenesService.obtener(id).then(setOrden).catch(setError).finally(() => setCargando(false)); }, [id]);
 if(cargando) return <div className="container py-4">Cargando boleta…</div>;
 if(error || !orden) return <div className="container py-4"><p role="alert">No se pudo encontrar la orden solicitada.</p><Link to="/admin/ordenes">Volver a órdenes</Link></div>;
 return <div className="container py-4"><div className="d-flex justify-content-between align-items-center mb-4"><div><span className="text-gold text-uppercase tracking-widest">Documento de venta</span><h1 className="luxury-title">Boleta #{orden.id}</h1></div><button className="btn btn-luxury" onClick={()=>window.print()}><i className="bi bi-printer me-2"/>Imprimir boleta</button></div><section className="luxury-card p-4"><div className="row g-4"><div className="col-md-6"><h2 className="h5 luxury-title">Datos del cliente</h2><p className="mb-1">{orden.cliente?.nombre} {orden.cliente?.apellidos}</p><p>{orden.cliente?.correo}</p></div><div className="col-md-6"><h2 className="h5 luxury-title">Orden y despacho</h2><p className="mb-1">Fecha: {new Date(orden.fecha).toLocaleString("es-CL")}</p><p className="mb-1">Estado: <strong>{orden.estado}</strong></p><p>{[orden.envio?.calle,orden.envio?.departamento,orden.envio?.comuna,orden.envio?.region].filter(Boolean).join(", ")}</p></div></div><div className="table-responsive"><table className="table table-dark table-hover align-middle"><thead><tr><th>Producto</th><th className="text-end">Precio</th><th className="text-end">Cantidad</th><th className="text-end">Subtotal</th></tr></thead><tbody>{orden.items?.map(i=><tr key={i.productoId}><td>{i.nombre}</td><td className="text-end">{formatearPrecio(i.precio)}</td><td className="text-end">{i.cantidad}</td><td className="text-end">{formatearPrecio(i.subtotal)}</td></tr>)}</tbody></table></div><div className="row justify-content-end"><div className="col-md-5"><div className="d-flex justify-content-between"><span>Subtotal</span><span>{formatearPrecio(orden.subtotal)}</span></div>{orden.cupon&&<div className="d-flex justify-content-between"><span>Descuento ({orden.cupon})</span><span>-{formatearPrecio(orden.descuento)}</span></div>}<hr/><div className="d-flex justify-content-between fs-5 fw-bold text-gold"><span>Total</span><span>{formatearPrecio(orden.total)}</span></div><small className="text-gold-light">Pago: {orden.pago?.metodo || "No informado"} · Tarjeta terminada en {orden.pago?.tarjetaFinal || "----"}</small></div></div></section><Link className="btn btn-outline-secondary mt-3" to="/admin/ordenes">Volver a órdenes</Link></div>;
}
