import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { productosService } from "../../services/productosService";
import { formatearPrecio } from "../../utils/formato";

export default function ProductosAdmin() {
  const [productos, setProductos] = useState([]);
  const [cargando, setCargando] = useState(true);
  const [error, setError] = useState("");
  const [busqueda, setBusqueda] = useState("");
  const [categoria, setCategoria] = useState("Todas");
  const [mensaje, setMensaje] = useState("");
  async function cargar() { setCargando(true); setError(""); try { setProductos(await productosService.listar()); } catch { setError("No se pudieron cargar los productos. Verifica que la API esté encendida."); } finally { setCargando(false); } }
  useEffect(() => { cargar(); }, []);
  const categorias = useMemo(() => ["Todas", ...new Set(productos.map(p => p.categoria).filter(Boolean))], [productos]);
  const filtrados = useMemo(() => { const q = busqueda.trim().toLowerCase(); return productos.filter(p => (categoria === "Todas" || p.categoria === categoria) && (!q || `${p.nombre} ${p.marca} ${p.codigo} ${p.id}`.toLowerCase().includes(q))); }, [productos, busqueda, categoria]);
  async function eliminar(producto) { if (!window.confirm(`¿Eliminar ${producto.nombre}?`)) return; try { await productosService.eliminar(producto.id); setProductos(prev => prev.filter(p => String(p.id) !== String(producto.id))); setMensaje("Producto eliminado correctamente."); } catch { setError("No se pudo eliminar el producto."); } }
  return <section className="admin-page container-fluid py-2">
    <div className="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><span className="admin-eyebrow">CATÁLOGO E INVENTARIO</span><h1 className="luxury-title display-5 mb-1">Productos</h1><p className="text-gold-light mb-0">Administra fragancias, precios y disponibilidad.</p></div><div className="d-flex flex-wrap gap-2"><Link className="btn btn-outline-light" to="/admin/productos/criticos"><i className="bi bi-exclamation-triangle me-2"/>Stock crítico</Link><Link className="btn btn-outline-light" to="/admin/productos/reportes"><i className="bi bi-bar-chart me-2"/>Reportes</Link><Link className="btn btn-luxury" to="/admin/productos/nuevo"><i className="bi bi-plus-lg me-2"/>Nuevo producto</Link></div></div>
    <div className="row g-3 mb-3"><div className="col-6 col-xl-3"><div className="admin-stat-card"><span>Productos</span><strong>{productos.length}</strong></div></div><div className="col-6 col-xl-3"><div className="admin-stat-card"><span>Stock total</span><strong>{productos.reduce((n,p)=>n+Number(p.stock||0),0)}</strong></div></div><div className="col-6 col-xl-3"><div className="admin-stat-card"><span>Stock crítico</span><strong>{productos.filter(p=>Number(p.stock||0)<=Number(p.stockCritico??2)).length}</strong></div></div><div className="col-6 col-xl-3"><div className="admin-stat-card"><span>Valor inventario</span><strong>{formatearPrecio(productos.reduce((n,p)=>n+Number(p.precio||0)*Number(p.stock||0),0))}</strong></div></div></div>
    <section className="admin-panel"><div className="row g-3 mb-4"><div className="col-12 col-lg-7"><label className="form-label" htmlFor="buscar-producto">Buscar producto</label><input id="buscar-producto" className="form-control admin-input" placeholder="Nombre, marca, código o ID" value={busqueda} onChange={e=>setBusqueda(e.target.value)}/></div><div className="col-12 col-lg-5"><label className="form-label" htmlFor="categoria-producto">Categoría</label><select id="categoria-producto" className="form-select admin-input" value={categoria} onChange={e=>setCategoria(e.target.value)}>{categorias.map(c=><option key={c}>{c}</option>)}</select></div></div>
    {mensaje && <div className="alert alert-success" role="status">{mensaje}</div>}{error && <div className="alert alert-warning" role="alert">{error}<button className="btn btn-sm btn-outline-dark ms-3" onClick={cargar}>Reintentar</button></div>}
    {cargando ? <p role="status">Cargando productos…</p> : filtrados.length ? <div className="table-responsive"><table className="table admin-table align-middle"><thead><tr><th>Producto</th><th>Código</th><th>Categoría</th><th className="text-end">Precio</th><th className="text-end">Stock</th><th>Estado</th><th className="text-end">Acciones</th></tr></thead><tbody>{filtrados.map(p=><tr key={p.id}><td><div className="d-flex align-items-center gap-3">{p.imagen && <img src={p.imagen} alt="" width="46" height="46" className="rounded object-fit-contain bg-white"/>}<div className="fw-semibold">{p.nombre}<small className="d-block text-secondary">{p.marca || "Sin marca"} · {p.ml || "—"} ml</small></div></div></td><td>{p.codigo || `#${p.id}`}</td><td>{p.categoria || "—"}</td><td className="text-end">{formatearPrecio(p.precio)}</td><td className="text-end">{p.stock ?? 0}</td><td><span className={`admin-status ${Number(p.stock||0)<=Number(p.stockCritico??2)?"pendiente":"pagada"}`}>{Number(p.stock||0)<=Number(p.stockCritico??2)?"Crítico":"Disponible"}</span></td><td><div className="d-flex justify-content-end gap-1"><Link className="btn btn-sm btn-outline-light" to={`/admin/productos/${p.id}`} aria-label={`Ver ${p.nombre}`}><i className="bi bi-eye"/></Link><Link className="btn btn-sm btn-outline-light" to={`/admin/productos/${p.id}/editar`} aria-label={`Editar ${p.nombre}`}><i className="bi bi-pencil"/></Link><button className="btn btn-sm btn-outline-danger" onClick={()=>eliminar(p)} aria-label={`Eliminar ${p.nombre}`}><i className="bi bi-trash"/></button></div></td></tr>)}</tbody></table></div> : <div className="admin-empty-state"><i className="bi bi-box-seam"/><h2 className="h5 luxury-title">No hay productos</h2><p>Prueba con otra búsqueda o crea un producto nuevo.</p><Link className="btn btn-luxury" to="/admin/productos/nuevo">Crear producto</Link></div>}
    {!cargando && <p className="small text-gold-light mb-0 mt-3">Mostrando {filtrados.length} de {productos.length} productos.</p>}</section></section>;
}
